### ISSUE TITLE
Doesn't work at all when collection view is created programmatically

### ISSUE THREAD

**Issue by gerchicov-bp** [simformsolutions/SSPlaceHolderTableView#2]
```
let collectonView = CollectionView(frame: .zero, collectionViewLayout: flowLayout)
```
Error:
```'CollectionView' initializer is inaccessible due to 'internal' protection level```

**Comment by brightroots7** [comment]
Yes it has an issue for its `private initializer`, copy the source file to your project and change the init, of `CollectionView` class with `public override init(frame: CGRect, collectionViewLayout layout: UICollectionViewLayout) `

**Comment by mobile-simformsolutions** [comment]
@gerchicov-bp  Issue fixed in the latest release. 

[#2.0.1](https://github.com/SimformSolutionsPvtLtd/SSPlaceHolderTableView/tree/2.0.1)
